#!/usr/bin/env python3
"""
qpu_spend_refresh.py — one-command refresh of the QPU spend accounting doc (Ember C4166).

Wraps the two existing probes:
  * check_usage.py   -> authoritative pool state (consumed / limit / window) via urllib
  * qpu_usage_tally.py logic -> per-backend + top jobs via the qiskit runtime service

...computes the pace flag, and rewrites the <!-- AUTO:BEGIN -->...<!-- AUTO:END --> block of
docs/qpu-usage-accounting-c4535.md. Numbers below the markers (narrative, method) are hand-kept.

USAGE:
  python3 scripts/qpu_spend_refresh.py            # dry-run: print the regenerated block, write nothing
  python3 scripts/qpu_spend_refresh.py --refresh  # rewrite the AUTO block in the doc

EXIT CODES: 0 ok · 1 pool exhausted (usage_limit_reached) · 2 credential/API/parse error

Fixed historical constants (not API-queryable — see the doc's Method section):
  OLD_PLAN_S      = 600   # Arc-1 old account, documented 600/600 EXHAUSTED (C4257)
  PRE_DRAWDOWN_S  = 1254  # C4535 measured tally, 118 jobs, May 22 - Jul 10 (pre-reset)
"""
import os
import sys
from collections import defaultdict
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

DOC = os.path.join(HERE, "..", "docs", "qpu-usage-accounting-c4535.md")
BEGIN = "<!-- AUTO:BEGIN — regenerated by scripts/qpu_spend_refresh.py; do not edit by hand -->"
END = "<!-- AUTO:END -->"

OLD_PLAN_S = 600
PRE_DRAWDOWN_S = 1254
PREMIUM_USD_PER_MIN = 96  # IBM pay-as-you-go Premium, for the $-equivalent context line


def _pool_state():
    """Authoritative pool state from check_usage.py's urllib helpers (no qiskit)."""
    import check_usage as cu
    token, crn = cu._load_account()
    bearer = cu._iam_token(token)
    hdr = {"Authorization": f"Bearer {bearer}", "Service-CRN": crn}
    usage = cu._get(f"{cu.API_BASE}/instances/usage", hdr)
    return {
        "consumed": float(usage["usage_consumed_seconds"]),
        "limit": float(usage["usage_limit_seconds"]),
        "reached": bool(usage.get("usage_limit_reached")),
        "start": usage["usage_period"]["start_time"],
        "end": usage["usage_period"]["end_time"],
    }


def _tally():
    """Per-backend sums + top jobs, via the same service getter the tally uses."""
    from run_exp66_qpu_partb import _get_ibm_service
    svc = _get_ibm_service()
    by_backend, rows, njobs = defaultdict(float), [], 0
    for job in svc.jobs(limit=500):
        try:
            u = None
            try:
                u = job.usage()
            except Exception:
                m = job.metrics()
                u = (m.get("usage", {}) or {}).get("seconds") or (m.get("usage", {}) or {}).get("quantum_seconds")
            if u is None:
                continue
            u = float(u)
            bk = getattr(job, "backend", lambda: None)()
            bname = getattr(bk, "name", str(bk)) if bk else "?"
            by_backend[bname] += u
            rows.append((str(job.job_id()), bname, u))
            njobs += 1
        except Exception:
            continue
    total = sum(by_backend.values())
    top = sorted(rows, key=lambda r: -r[2])[:5]
    return njobs, total, dict(by_backend), top


def _fmt(n):
    return f"{n:,.1f}" if n % 1 else f"{int(n):,}"


def _iso(s):
    return datetime.fromisoformat(s.replace("Z", "+00:00"))


def build_block(pool, njobs, tally_total, by_backend, top):
    now = datetime.now(timezone.utc)
    consumed, limit = pool["consumed"], pool["limit"]
    remaining = max(0.0, limit - consumed)
    pct = 100.0 * consumed / limit if limit else float("nan")
    start, end = _iso(pool["start"]), _iso(pool["end"])
    days = (now - start).total_seconds() / 86400.0
    burn = consumed / days if days > 0 else float("nan")
    straight = limit / 365.0
    ratio = burn / straight if straight else float("nan")
    days_left_burst = remaining / burn if burn > 0 else float("inf")
    days_remaining_window = max(1.0, (end - now).total_seconds() / 86400.0)
    fit_rate = remaining / days_remaining_window
    reconc = "**exactly**" if abs(tally_total - consumed) < 1.0 else f"**within {abs(tally_total-consumed):.0f}s**"

    lifetime = OLD_PLAN_S + PRE_DRAWDOWN_S + consumed
    lifetime_min = lifetime / 60.0
    usd = lifetime_min * PREMIUM_USD_PER_MIN

    bk_lines = "\n".join(
        f"| {b} | {v:,.1f} | {100*v/tally_total:.1f}% |"
        for b, v in sorted(by_backend.items(), key=lambda kv: -kv[1])
    )
    top_line = " · ".join(f"{u:,.1f}s `{jid[:8]}…` ({b})" for jid, b, u in top)
    verdict = ("🔴 EXHAUSTED — `usage_limit_reached: true`" if pool["reached"]
               else "🟢 AVAILABLE — `usage_limit_reached: false`")

    return f"""{BEGIN}
**Latest refresh: {now:%Y-%m-%d %H:%M} UTC** (`scripts/check_usage.py` + `scripts/qpu_usage_tally.py`).
Prior narrative refresh: Whisper C4535, 2026-07-10.

---

## CURRENT POOL — authoritative (IBM API)

The C4536 propagation lag is **resolved** — the API reports the upgraded pool directly
(`usage_limit_seconds: {int(limit):,}`, no longer stuck at 600):

| | QPU-seconds |
|---|---|
| **Consumed** | **{_fmt(consumed)} / {int(limit):,} ({pct:.1f}%)** |
| **Remaining** | **{_fmt(remaining)}** |
| Window | {start:%Y-%m-%d %H:%M} UTC → {end:%Y-%m-%d %H:%M} UTC (12-month drawdown) |
| Verdict | {verdict} |

The tally reconciles {reconc}: {njobs} jobs enumerated on the account, all DONE-with-usage,
summing to **{_fmt(tally_total)}s** vs the API's `usage_consumed_seconds` = **{_fmt(consumed)}s**.

### This pool by backend ({njobs} jobs)
| Backend | QPU-s | share |
|---|---|---|
{bk_lines}

Largest jobs: {top_line}.

## ⚠️ PACE FLAG

The pool opened {start:%Y-%m-%d}; **in its first {days:.1f} days it consumed {pct:.1f}% of the annual budget**.

- Burn rate to date: **{burn:.1f} QPU-s/day** — **{ratio:.1f}× the straight-line guide** ({int(limit):,} ÷ 365 = {straight:.1f} s/day).
- At this cadence the remaining {_fmt(remaining)}s lasts **~{days_left_burst:.0f} more days**.
- To fit the 12-month window, the remaining budget must average **≤ {fit_rate:.1f} s/day** for ~{days_remaining_window:.0f} days.

**Read**: a front-loaded burst, not steady-state — see the narrative below the markers for which arc
drove it. Steer back toward the 900 s/mo straight-line pace between sprints (C4536 policy).

## LIFETIME CAMPAIGN ESTIMATE (all eras)

| Era | QPU-s | Basis |
|---|---|---|
| Arc-1 old plan (exhausted) | ≈ {OLD_PLAN_S} | documented 600/600 EXHAUSTED (C4257); not re-queryable |
| Open-plan, pre-drawdown (May 22 – Jul 10) | {PRE_DRAWDOWN_S:,} | C4535 measured tally, 118 jobs |
| Drawdown pool (Jul 10 →) | {_fmt(consumed)} | this refresh, {njobs} jobs, API-confirmed |
| **Lifetime total** | **≈ {_fmt(lifetime)} s ≈ {lifetime_min:.1f} min** | ~185+ jobs, 3 Heron devices, since May 22 2026 |

At IBM pay-as-you-go Premium (~${PREMIUM_USD_PER_MIN}/QPU-min), ~{lifetime_min:.1f} QPU-min ≈ **${usd:,.0f}-equivalent** of execution,
obtained on free/allocated quota.
{END}"""


def main():
    write = "--refresh" in sys.argv
    try:
        pool = _pool_state()
    except Exception as e:
        print(f"❌ Pool-state error: {e}")
        return 2
    try:
        njobs, tally_total, by_backend, top = _tally()
    except Exception as e:
        print(f"❌ Tally error: {e}")
        return 2

    block = build_block(pool, njobs, tally_total, by_backend, top)

    if not write:
        print(block)
        print("\n[dry-run] pass --refresh to write docs/qpu-usage-accounting-c4535.md", file=sys.stderr)
        return 1 if pool["reached"] else 0

    with open(DOC, encoding="utf-8") as fh:
        doc = fh.read()
    if BEGIN not in doc or END not in doc:
        print(f"❌ AUTO markers not found in {DOC}", file=sys.stderr)
        return 2
    pre, _, rest = doc.partition(BEGIN)
    _, _, post = rest.partition(END)
    with open(DOC, "w", encoding="utf-8") as fh:
        fh.write(pre + block + post)
    print(f"✅ Refreshed AUTO block in {os.path.relpath(DOC, HERE)}")
    print(f"   consumed {pool['consumed']:.0f}/{pool['limit']:.0f}s · {njobs} jobs · tally {tally_total:.0f}s")
    return 1 if pool["reached"] else 0


if __name__ == "__main__":
    sys.exit(main())
