#!/usr/bin/env python3
"""
Exp68 — Prime-N CNOT Ring Entangling Power Test

Author: Whisper (DC15W) | Cycle: C4391 | 2026-06-26

Tests whether prime-N CNOT-ring circuits have higher entangling power than
composite-N rings, extending Ember's classical IIT finding into quantum domain.

Key design insight: CNOT gates map |+>^N → |+>^N trivially (uniform superposition
is invariant under all permutations). We instead measure ENTANGLING POWER —
average entanglement generated over random product-state inputs. This tests
whether the prime-N topology makes the unitary "more entangling" on average,
the quantum analog of GF(2) irreducibility → high Phi.

Pre-registration: experiments/exp68-prime-ring-iit-preregistration.md (updated)
Pearl bridge: Whisper C4389 (GF(2) irreducibility → causal non-decomposability)
"""

import json
import numpy as np
from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector, partial_trace, entropy, random_statevector


# Fixed seed for reproducibility
RNG = np.random.default_rng(42)
N_RANDOM_INPUTS = 500  # product states to average over per N


def build_cnot_ring_unitary(n: int) -> np.ndarray:
    """Build the N×N unitary matrix of the CNOT ring (no initial state)."""
    qc = QuantumCircuit(n)
    for i in range(n):
        qc.cx(i, (i + 1) % n)
    sv = Statevector(qc)
    return np.array(sv.data).reshape(2**n, 2**n, order='F')  # unitary cols from ket inputs


def build_cnot_ring_circuit_only(n: int) -> QuantumCircuit:
    """CNOT ring circuit without initial state prep."""
    qc = QuantumCircuit(n)
    for i in range(n):
        qc.cx(i, (i + 1) % n)
    return qc


def random_product_state(n: int) -> np.ndarray:
    """Generate a random N-qubit product state (tensor product of single-qubit random states)."""
    # Each single qubit: random point on Bloch sphere
    state = np.array([1.0], dtype=complex)
    for _ in range(n):
        theta = RNG.uniform(0, np.pi)
        phi = RNG.uniform(0, 2 * np.pi)
        qubit = np.array([np.cos(theta / 2), np.exp(1j * phi) * np.sin(theta / 2)])
        state = np.kron(state, qubit)
    return state


def meyer_wallach_q_from_array(state_arr: np.ndarray, n: int) -> float:
    """Meyer-Wallach Q from raw state vector array."""
    sv = Statevector(state_arr)
    q_sum = 0.0
    for i in range(n):
        others = [j for j in range(n) if j != i]
        rho_i = partial_trace(sv, others)
        rho_arr = np.array(rho_i.data)
        purity = float(np.real(np.trace(rho_arr @ rho_arr)))
        q_sum += (1.0 - purity)
    return (4.0 / n) * q_sum


def mean_bipartite_entropy_from_array(state_arr: np.ndarray, n: int) -> float:
    """Mean bipartite entropy over all single-qubit subsystems."""
    sv = Statevector(state_arr)
    entropies = []
    for i in range(n):
        others = [j for j in range(n) if j != i]
        rho_i = partial_trace(sv, others)
        s = entropy(rho_i, base=2)
        entropies.append(float(s))
    return float(np.mean(entropies))


def compute_entangling_power(n: int, k: int = N_RANDOM_INPUTS) -> dict:
    """
    Compute entangling power of CNOT ring for N qubits.

    Entangling power = average entanglement generated by the unitary
    over K random product-state inputs.

    Also tracks:
    - Distribution of Q values (to check if it's bimodal)
    - Comparison: input Q vs output Q
    """
    qc = build_cnot_ring_circuit_only(n)
    is_prime = n in {2, 3, 5, 7, 11, 13}

    q_input_list = []
    q_output_list = []
    s_output_list = []

    for _ in range(k):
        # Random product state
        input_arr = random_product_state(n)

        # Measure input Q (should be ~0 for product states)
        q_in = meyer_wallach_q_from_array(input_arr, n)
        q_input_list.append(q_in)

        # Apply CNOT ring: evolve state through circuit
        input_sv = Statevector(input_arr)
        output_sv = input_sv.evolve(qc)
        output_arr = np.array(output_sv.data)

        # Measure output entanglement
        q_out = meyer_wallach_q_from_array(output_arr, n)
        q_output_list.append(q_out)

        s_out = mean_bipartite_entropy_from_array(output_arr, n)
        s_output_list.append(s_out)

    q_inputs = np.array(q_input_list)
    q_outputs = np.array(q_output_list)
    s_outputs = np.array(s_output_list)

    # Entangling power = mean Q generated (output - input)
    entangling_power_q = float(np.mean(q_outputs - q_inputs))

    return {
        "n": n,
        "is_prime": is_prime,
        "n_samples": k,
        "entangling_power_Q": entangling_power_q,
        "mean_output_Q": float(np.mean(q_outputs)),
        "std_output_Q": float(np.std(q_outputs)),
        "mean_output_entropy": float(np.mean(s_outputs)),
        "std_output_entropy": float(np.std(s_outputs)),
        "mean_input_Q": float(np.mean(q_inputs)),
        "fraction_Q_above_0.5": float(np.mean(q_outputs > 0.5)),
    }


def analyze_operator_structure(n: int) -> dict:
    """
    Analyze the algebraic structure of the CNOT ring unitary.
    Tests if the unitary can be factored as U_A ⊗ U_B for any bipartition.

    A FACTORIZABLE unitary has low entangling power (like a product channel).
    An IRREDUCIBLE unitary cannot be factored — quantum causal non-decomposability.

    Method: For each bipartition A|B, check if the unitary matrix approx factors.
    Schmidt rank of Choi matrix = 1 iff the channel is a product channel.
    """
    qc = build_cnot_ring_circuit_only(n)
    is_prime = n in {2, 3, 5, 7, 11, 13}

    # Get the full unitary matrix
    # Use Statevector on basis states to reconstruct U column by column
    U = np.zeros((2**n, 2**n), dtype=complex)
    for k in range(2**n):
        basis_arr = np.zeros(2**n, dtype=complex)
        basis_arr[k] = 1.0
        sv_in = Statevector(basis_arr)
        sv_out = sv_in.evolve(qc)
        U[:, k] = np.array(sv_out.data)

    # For each bipartition i|rest, compute the operator Schmidt rank
    # U can be written as sum_k A_k ⊗ B_k
    # Number of non-negligible terms = operator Schmidt rank
    # If rank = 1, U factors as A ⊗ B (low entangling power)

    bipartition_ranks = []
    for i in range(n):
        # Bipartition: qubit i vs rest
        dim_a = 2  # qubit i
        dim_b = 2 ** (n - 1)

        # Reshape U into (dim_a, dim_b, dim_a, dim_b) and compute Schmidt rank
        # Using Choi matrix approach: C = (I_a ⊗ U) |Φ+⟩⟨Φ+|
        # For unitary channels, Choi = vec(U) vec(U)^dag, rank always = 1 (pure Choi)
        # Better: use operator Schmidt decomposition of U viewed as element of H_a ⊗ H_b ⊗ H_a ⊗ H_b

        # Reshape U (dim, dim) as (dim_a, dim_b, dim_a, dim_b)
        # Qiskit convention: qubit ordering is little-endian (qubit 0 is least significant)
        # For qubit i bipartition: A=qubit i, B=all others

        # Permute to bring qubit i to the front
        perm = [i] + [j for j in range(n) if j != i]  # qubit indices in new order
        # Build full permutation on 2^n state space
        U_reshaped = U.reshape([2] * n + [2] * n)

        # Reorder input indices (second half of axes = input qubits)
        in_perm = [n + p for p in perm]  # input axes
        out_perm = perm  # output axes
        full_perm = out_perm + in_perm
        U_permuted = np.transpose(U_reshaped, full_perm)

        # Reshape: (dim_a, dim_b, dim_a, dim_b) → (dim_a * dim_a, dim_b * dim_b)
        # This is the natural bipartition for operator Schmidt rank
        U_mat = U_permuted.reshape(dim_a * dim_a, dim_b * dim_b)

        # SVD to get Schmidt rank (number of non-negligible singular values)
        sv = np.linalg.svd(U_mat, compute_uv=False)
        threshold = 1e-10 * sv[0]
        rank = int(np.sum(sv > threshold))
        bipartition_ranks.append({"qubit": i, "operator_schmidt_rank": rank})

    min_rank = min(r["operator_schmidt_rank"] for r in bipartition_ranks)
    max_rank = max(r["operator_schmidt_rank"] for r in bipartition_ranks)
    mean_rank = float(np.mean([r["operator_schmidt_rank"] for r in bipartition_ranks]))

    return {
        "n": n,
        "is_prime": is_prime,
        "bipartition_ranks": bipartition_ranks,
        "min_operator_schmidt_rank": min_rank,
        "max_operator_schmidt_rank": max_rank,
        "mean_operator_schmidt_rank": mean_rank,
        "is_product_unitary": (min_rank == 1),
    }


def grade_hypotheses(results: dict, structure: dict) -> dict:
    """Grade pre-registered hypotheses H1 and H2 (revised for entangling power)."""

    # H1 (revised): Entangling power (mean output Q) higher for prime-N
    h1_a = results[5]["mean_output_Q"] > results[4]["mean_output_Q"]
    h1_b = results[7]["mean_output_Q"] > results[6]["mean_output_Q"]
    h1_pass = h1_a and h1_b
    h1_note = (
        f"N=5 vs N=4: {results[5]['mean_output_Q']:.4f} vs {results[4]['mean_output_Q']:.4f} → "
        f"{'PASS' if h1_a else 'FAIL'} | "
        f"N=7 vs N=6: {results[7]['mean_output_Q']:.4f} vs {results[6]['mean_output_Q']:.4f} → "
        f"{'PASS' if h1_b else 'FAIL'}"
    )

    # H2 (revised): Operator Schmidt rank higher (more non-factorizable) for prime-N
    h2_a = structure[5]["mean_operator_schmidt_rank"] > structure[4]["mean_operator_schmidt_rank"]
    h2_b = structure[7]["mean_operator_schmidt_rank"] > structure[6]["mean_operator_schmidt_rank"]
    h2_pass = h2_a and h2_b
    h2_note = (
        f"N=5 vs N=4 Schmidt rank: {structure[5]['mean_operator_schmidt_rank']:.2f} vs "
        f"{structure[4]['mean_operator_schmidt_rank']:.2f} → {'PASS' if h2_a else 'FAIL'} | "
        f"N=7 vs N=6: {structure[7]['mean_operator_schmidt_rank']:.2f} vs "
        f"{structure[6]['mean_operator_schmidt_rank']:.2f} → {'PASS' if h2_b else 'FAIL'}"
    )

    # H3 (exploratory): N=7 has highest mean output Q
    q_by_n = {n: results[n]["mean_output_Q"] for n in results}
    h3_pass = max(q_by_n, key=q_by_n.get) == 7

    return {
        "H1_entangling_power": {"verdict": "PASS" if h1_pass else "FAIL", "detail": h1_note},
        "H2_schmidt_rank": {"verdict": "PASS" if h2_pass else "FAIL", "detail": h2_note},
        "H3_exploratory": {
            "verdict": "PASS" if h3_pass else "FAIL",
            "detail": f"Max Q at N={max(q_by_n, key=q_by_n.get)}: {max(q_by_n.values()):.4f}"
        },
    }


def main():
    print("=" * 70)
    print("Exp68 — Prime-N CNOT Ring Entangling Power Test")
    print("Author: Whisper (DC15W) | Cycle: C4391 | 2026-06-26")
    print("=" * 70)
    print()
    print("NOTE: Revised from initial design. |+>^N is invariant under CNOT")
    print("(CNOT acts trivially on uniform superposition — a permutation on basis).")
    print("Instead: measuring ENTANGLING POWER over random product-state inputs.")
    print()

    results = {}
    structure = {}

    classical_phi = {3: 1.875, 4: 0.0, 5: 15.156, 6: 1.875, 7: 49.609}

    print("Phase 1: Operator Schmidt rank (structural analysis)")
    print("-" * 50)
    for n in [3, 4, 5, 6, 7]:
        s = analyze_operator_structure(n)
        structure[n] = s
        prime_str = "PRIME" if s["is_prime"] else "COMPOSITE"
        print(f"N={n} ({prime_str}): mean Schmidt rank = {s['mean_operator_schmidt_rank']:.2f}, "
              f"min={s['min_operator_schmidt_rank']}, max={s['max_operator_schmidt_rank']}, "
              f"product_unitary={s['is_product_unitary']}")
    print()

    print(f"Phase 2: Entangling power ({N_RANDOM_INPUTS} random product-state inputs per N)")
    print("-" * 50)
    for n in [3, 4, 5, 6, 7]:
        r = compute_entangling_power(n)
        results[n] = r
        prime_str = "PRIME" if r["is_prime"] else "COMPOSITE"
        print(f"N={n} ({prime_str}):")
        print(f"  Mean output Q:     {r['mean_output_Q']:.4f} ± {r['std_output_Q']:.4f}")
        print(f"  Entangling power:  {r['entangling_power_Q']:.4f} (Q_out - Q_in)")
        print(f"  Mean output S:     {r['mean_output_entropy']:.4f}")
        print(f"  Frac Q > 0.5:      {r['fraction_Q_above_0.5']:.3f}")
        print()

    print("=" * 70)
    print("HYPOTHESIS GRADING (pre-registered, revised for entangling power)")
    print("=" * 70)
    grades = grade_hypotheses(results, structure)
    for h, v in grades.items():
        print(f"{h}: {v['verdict']}")
        print(f"  {v['detail']}")
    print()

    print("=" * 70)
    print("CLASSICAL PHI vs QUANTUM ENTANGLING POWER")
    print("=" * 70)
    print(f"{'N':>3}  {'Prime':>8}  {'Cl. Phi':>10}  {'Mean Q out':>12}  {'Entangling Power':>18}  {'Schmidt rank':>14}")
    print("-" * 75)
    for n in [3, 4, 5, 6, 7]:
        r = results[n]
        s = structure[n]
        prime = "YES" if r["is_prime"] else "NO"
        print(f"{n:>3}  {prime:>8}  {classical_phi[n]:>10.3f}  {r['mean_output_Q']:>12.4f}"
              f"  {r['entangling_power_Q']:>18.4f}  {s['mean_operator_schmidt_rank']:>14.2f}")

    print()
    print("=" * 70)
    print("PEARL BRIDGE INTERPRETATION")
    print("=" * 70)
    phi_values = [classical_phi[n] for n in [3, 4, 5, 6, 7]]
    q_values = [results[n]["mean_output_Q"] for n in [3, 4, 5, 6, 7]]
    schmidt_values = [structure[n]["mean_operator_schmidt_rank"] for n in [3, 4, 5, 6, 7]]

    corr_phi_q = np.corrcoef(phi_values, q_values)[0, 1]
    corr_phi_schmidt = np.corrcoef(phi_values, schmidt_values)[0, 1]

    print(f"Correlation (classical Phi vs quantum Q_out): r = {corr_phi_q:.4f}")
    print(f"Correlation (classical Phi vs Schmidt rank):  r = {corr_phi_schmidt:.4f}")

    if abs(corr_phi_q) > 0.7:
        print("→ HIGH correlation: classical Phi tracks quantum entangling power")
        print("  Pearl bridge SUPPORTED: GF(2) irreducibility → quantum causal non-decomposability")
    elif abs(corr_phi_q) > 0.4:
        print("→ MODERATE correlation: partial quantum-classical Phi alignment")
        print("  Pearl bridge PARTIAL: quantum effects modify but preserve structure")
    else:
        print("→ LOW correlation: classical Phi and quantum entangling power diverge")
        print("  Pearl bridge NOT SUPPORTED in this quantum extension")
        print("  Interpretation: quantum mechanics introduces new topology effects")

    print()
    print("PRODUCT UNITARY CHECK:")
    for n in [3, 4, 5, 6, 7]:
        s = structure[n]
        prime_str = "PRIME" if s["is_prime"] else "COMPOSITE"
        factorizable = "PRODUCT (factorizable)" if s["is_product_unitary"] else "IRREDUCIBLE (non-factorizable)"
        print(f"  N={n} ({prime_str}): {factorizable}")

    # Save results
    output = {
        "experiment": "exp68",
        "version": "v2_entangling_power",
        "cycle": "C4391",
        "author": "Whisper (DC15W)",
        "date": "2026-06-26",
        "design_note": "Revised: |+>^N invariant under CNOT; using entangling power over random product states",
        "hypothesis_grades": grades,
        "entangling_power_results": results,
        "operator_structure": structure,
        "classical_phi": classical_phi,
        "correlations": {
            "phi_vs_mean_Q_out": float(corr_phi_q),
            "phi_vs_schmidt_rank": float(corr_phi_schmidt),
        },
    }

    out_path = "/droid/repos/quantum/experiments/exp68_results.json"
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2, default=str)
    print(f"\nResults saved: {out_path}")

    return output


if __name__ == "__main__":
    main()
